project_id: "569777"
api_token_env: CROWDIN_API_TOKEN
commit_message: "Change(i18n): sync translations of %language%"
append_commit_message: false
pull_request_title: "Change(i18n): sync translations from Crowdin"
pull_request_labels:
  - language
files:
  - source: /locales/ja/*.json
    translation: /locales/%locale%/%original_file_name%
    type: i18next_json
  - source: /README.md
    translation: /locales/README.%locale%.md
